### PR TITLE
add bleve

### PR DESCRIPTION
**Pull request by 1l0**
Add [bleve](https://github.com/blevesearch/bleve). It's not battle-tested.

### CODE REVIEW

**Comment by fiatjaf** [comment]
Is this different from the bluge backend? Is it based on that?

**Comment by 1l0** [comment]
I use bleve just because bluge is abandoned. It feels same to me so far. Never mind if you reject this.

**Comment by fiatjaf** [comment]
We can definitely merge this. My question was just if the code here was adapted from the bluge code and worked the same way.

**Comment by 1l0** [comment]
Oh yea this is the modified version of your bluge code and worked for my purpose but wait, your comments raise concerns regarding the test coverage. I'm going to close this at the moment.

**Pull request closed without merging**
