### PR TITLE
add search

### PR DESCRIPTION
**Pull request by pablof7z**
this is probably wrong, naive, and vulnerable to all kinds of attacks

but it works

Screenshot 2024-02-27 at 11 40 17 AM

### CODE REVIEW

**Comment by mattn** [comment]
query.go already have a code for search. (please look about 10 lines following)

**Comment by fiatjaf** [comment]
That is not for search, it's for querying tags.

**Comment by fiatjaf** [comment]
But I still don't like this PR.

**Comment by fiatjaf** [comment]
However it could work if this behavior was hidden behind an initialization flag on the DB object.

**Comment by fiatjaf** [comment]
Ideally NIP-50 would use https://www.sqlite.org/fts5.html though.

**Comment by mattn** [comment]
No, I already implemented this with same code.

[Screencast from 2024年05月29日 18時42分56秒.webm](https://github.com/fiatjaf/eventstore/assets/10111/395a6fb0-787c-4fca-b88c-40f52c673ae1)

**Pull request closed without merging**
